" Don't try to be vi compatible
set nocompatible

" Plugins
call plug#begin()
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-fugitive'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'pangloss/vim-javascript'
Plug 'leafgarland/typescript-vim'
Plug 'peitalin/vim-jsx-typescript'
call plug#end()

" For plugins to load correctly
filetype plugin indent on

" Turn on syntax highlighting
syntax on

" TODO: Pick a leader key
let mapleader = ","

" swap dir
set directory=$HOME/.vim/swapfiles//

" Security
set modelines=0

" Show line numbers
set number

" Show file stats
set ruler

" Blink cursor on error instead of beeping (grr)
set visualbell

" Encoding
set encoding=utf-8

" Whitespace
set formatoptions=tcqrn1
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set noshiftround

" Cursor motion
set scrolloff=3
set backspace=indent,eol,start
set matchpairs+=<:> " use % to jump between pairs
runtime! macros/matchit.vim

" Move up/down editor lines
nnoremap j gj
nnoremap k gk

" Allow hidden buffers
set hidden

" Rendering
set ttyfast

" Status bar
set laststatus=2

" Last line
set showmode
set showcmd

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
map <leader><space> :let @/=''<cr> " clear search

" escape from insert mode
inoremap jj <Esc>

" simple complete pevious word
inoremap <leader>q <C-p>

" simple complete next word
inoremap <leader>w <C-n>

" cycle next buffer
nnoremap <leader>x :bnext<cr>

" cycle previous buffer
nnoremap <leader>z :bprevious<cr>

" save file
nnoremap <leader>s :w<cr>

" nerdtree
nnoremap <leader>c :NERDTreeToggle<cr>

" vim fugative
nnoremap <leader><leader>gs :Gstatus<cr>
nnoremap <leader><leader>gd :Gdiff<cr>

" javascript spacing 4 spaces insted of the default 2
" autocmd Filetype javascript setlocal ts=4 sw=4 sts=0 expandtab
autocmd Filetype python setlocal ts=4 sw=4 sts=0 expandtab
autocmd Filetype c setlocal ts=4 sw=4 sts=0 expandtab
autocmd Filetype cpp setlocal ts=4 sw=4 sts=0 expandtab
autocmd Filetype go setlocal ts=4 sw=4 sts=0 expandtab

" set filetypes as typescript.tsx
autocmd BufNewFile,BufRead *.tsx,*.jsx set filetype=typescript.tsx

" fix nerdtree whitespace
let g:NERDTreeNodeDelimiter = "\u00a0"

set wildignore+=*/node_modules/*,*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(exe|so|dll)$',
  \ }

" typical cursor config
let &t_SI = "\<esc>[5 q"  " blinking I-beam in insert mode
let &t_SR = "\<esc>[3 q"  " blinking underline in replace mode
let &t_EI = "\<esc>[ q"  " default cursor (usually blinking block) otherwise
